name: ohud
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  iconsax: ^0.0.8
  material_symbols_icons: ^4.2811.0
  mobile_scanner: ^6.0.7
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_native_splash:
  color: "#FFFAEEFF"
  image: assets/images/2.png
  android_12:
    color: "#FFFAEEFF"
    image: assets/images/2.png


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/1.png
    - assets/images/2.png

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
